-- ============================================================================
-- CROMPTON Solar Monitor - Database Schema for Supabase
-- Single-Solar-Panel Monitoring & Soiling-Loss Intelligence
-- ============================================================================

-- 1. Solar Panel Telemetry Readings Table
CREATE TABLE IF NOT EXISTS public.solar_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    node_id TEXT NOT NULL DEFAULT 'CR-SOLAR-001',
    voltage DOUBLE PRECISION NOT NULL,
    current DOUBLE PRECISION NOT NULL,
    power DOUBLE PRECISION NOT NULL,
    panel_temperature DOUBLE PRECISION
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_solar_readings_timestamp ON public.solar_readings (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_solar_readings_node_id ON public.solar_readings (node_id);

-- 2. Weather & Environmental Readings Table
CREATE TABLE IF NOT EXISTS public.weather_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    temperature DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    solar_radiation DOUBLE PRECISION,
    cloud_cover DOUBLE PRECISION,
    rainfall DOUBLE PRECISION,
    wind_speed DOUBLE PRECISION
);

-- Index for weather queries
CREATE INDEX IF NOT EXISTS idx_weather_readings_timestamp ON public.weather_readings (timestamp DESC);

-- 3. AI & Soiling Loss Predictions Table
CREATE TABLE IF NOT EXISTS public.predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    expected_power DOUBLE PRECISION NOT NULL,
    actual_power DOUBLE PRECISION NOT NULL,
    soiling_loss_percent DOUBLE PRECISION NOT NULL,
    energy_loss DOUBLE PRECISION DEFAULT 0.0,
    estimated_cost_loss DOUBLE PRECISION DEFAULT 0.0,
    cleaning_status TEXT DEFAULT 'NORMAL'
);

-- Index for predictions queries
CREATE INDEX IF NOT EXISTS idx_predictions_timestamp ON public.predictions (timestamp DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.solar_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weather_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;

-- Permissive policies for anon and authenticated API key access
DO $$
BEGIN
    -- Solar readings policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow read access to solar_readings' AND tablename = 'solar_readings') THEN
        CREATE POLICY "Allow read access to solar_readings" ON public.solar_readings FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow insert to solar_readings' AND tablename = 'solar_readings') THEN
        CREATE POLICY "Allow insert to solar_readings" ON public.solar_readings FOR INSERT WITH CHECK (true);
    END IF;

    -- Weather readings policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow read access to weather_readings' AND tablename = 'weather_readings') THEN
        CREATE POLICY "Allow read access to weather_readings" ON public.weather_readings FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow insert to weather_readings' AND tablename = 'weather_readings') THEN
        CREATE POLICY "Allow insert to weather_readings" ON public.weather_readings FOR INSERT WITH CHECK (true);
    END IF;

    -- Predictions policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow read access to predictions' AND tablename = 'predictions') THEN
        CREATE POLICY "Allow read access to predictions" ON public.predictions FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow insert to predictions' AND tablename = 'predictions') THEN
        CREATE POLICY "Allow insert to predictions" ON public.predictions FOR INSERT WITH CHECK (true);
    END IF;
END $$;
